server:
  port: 5000

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - '*'
              #- 'http://localhost:7000'
              #- 'http://localhost:7001'
              #- 'http://15.165.135.23:5000'
              #- 'http://thxforservice.xyz'
              #- 'http://www.thxforservice.xyz'
            #allowCredentials: true # 요청시 인증 정보 전송 허가
            allowedHeaders: '*'
            allowedMethods: '*'
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true

      routes:
        - id: memberservice
          uri: lb://memberservice
          predicates:
              - Path=/api/v1/member/**
          filters:
              - RewritePath=/api/v1/member/?(?<path>.*),/$\{path}
        - id: boardservice
          uri: lb://boardservice
          predicates:
              - Path=/api/v1/board/**
          filters:
              - RewritePath=/api/v1/board/?(?<path>.*),/$\{path}
        - id: fileservice
          uri: lb://fileservice
          predicates:
              - Path=/api/v1/file/**
          filters:
              - RewritePath=/api/v1/file/?(?<path>.*),/$\{path}
        - id: reservationservice
          uri: lb://reservationservice
          predicates:
              - Path=/api/v1/reservation/**
          filters:
              - RewritePath=/api/v1/reservation/?(?<path>.*),/$\{path}
        - id: surveyservice
          uri: lb://surveyservice
          predicates:
              - Path=/api/v1/survey/**
          filters:
              - RewritePath=/api/v1/survey/?(?<path>.*),/$\{path}
        - id: chattingservice
          uri: lb://chattingservice
          predicates:
              - Path=/api/v1/chatting/**
          filters:
              - RewritePath=/api/v1/chatting/?(?<path>.*),/$\{path}

# 유레카 설정
eureka:
  instance:
    hostname: ${hostname}
    #preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eurekaHost}/eureka/

# 액츄에이터 설정
management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: gateway
